# Make a site for a workshop

```{r, include = FALSE}
source("common.R")
```

Here are some components that your workshop site should have. 

1) General Information: Where, When, Requirements (i.e. "bring a laptop, install this software"), Code of Conduct, Accesibility info, 
2) Schedule
3) Syllabus/ Learning Objectives
4) Pre-Work/ Setup info (what packages to install)
5) Access to Lesson Materials (via link, download, or package)

Here are some examples of three different workshop sites that use these components (not necessarily made in R Markdown, but just to give you an idea of what you should be putting in yours.)

1) [Software Carpentry Template](http://carpentries.github.io/workshop-template/)
2) [anglea-li/sotmus-r](https://github.com/angela-li/sotmus-r): Simple, clean layout for workshop info. It's only a README.md!
3) 

Here's how you can build each of these components:

### Thing 1


### Thing 2


### Thing 3


Here's a link to a bare bones demo workshop site that we've made and it's repository.

Here's a link to a bare bones demo workshop site that we've made and it's repository.

### Some extra cool stuff we've seen

[Having the Schedule times determined by a script](https://github.com/rstudio-education/deep-teaching/blob/master/course-planning/outline.Rmd)

