# (PART\*) Four basic ingredients {-}

```{r, include = FALSE}
source("common.R")
```

# Infrastructure {#edu-stack}

## R {#capital-r}

Recommended: don't install R via Homebrew. If you insist on using Homebrew, do *not* use 

## RStudio {#rstudio}

### The RStudio IDE {#rstudio-ide}

You can use only R, but using RStudio can save you a lot of headache and a lot of time! Best analogy ever: https://moderndive.com/2-getting-started.html#r-rstudio

https://happygitwithr.com/install-r-rstudio.html

### RStudio Projects {#rstudio-proj}

### RStudio.cloud {#rstudio-cloud}

### Pro Products {#rstudio-pro}

https://www.rstudio.com/pricing/academic-pricing/

## GitHub {#github}

### GitHub for you {#gh-for-you}

Why educators should use version control, high-level thoughts

### GitHub for them {#gh-for-them}

Resources for integrating GitHub for learners; not our primary focus here, outsource to:

Make sure to mention Mine's ghclass package

Happy Git with R for yourself and your students

GitHub Classroom is also a good option to consider

https://happygitwithr.com/classroom-overview.html


https://r4ds.had.co.nz/workflow-projects.html

https://docs.google.com/document/d/132hdA_2U8-thkF3yd_xUUsBFviQGOL-_zpaEZRSwjro/edit?usp=sharing

## Communication platform

Options: Slack (recommended for longer term teaching, like courses), gitter (recommended for workshops)
